### ISSUE TITLE
Docker and Singularity support 

### ISSUE THREAD

**Issue by flat35hd99** [yamatolab/current-calculations-for-proteins#15]
Container support. Docker needs root but Docker container can be converted into singularity container.

**Comment by passive-radio** [comment]
curp singularity container image for v1.3 was added in 2022.

You can build a container for CURP. Example code below.
```
singularity pull curp_singularity.sif oras://ghcr.io/passive-radio/curp-singularity:latest
singularity test curp_singularity.sif
```
