### ISSUE TITLE
Spelling mistake in doc files

### ISSUE THREAD

**Issue by zorowangtt** [yamatolab/current-calculations-for-proteins#5]
I found two mistakes in file ~/current-calculations-for-proteins/docs/source/eflow_tutorial.rst
Line 184 and 202: “curp **convtrj** -vel \“(Original)
I think it should be “curp **conv-trj** -vel \” ….

**Comment by flat35hd99** [comment]
@zorowangtt Thank you report!

https://github.com/yamatolab/current-calculations-for-proteins/blame/master/docs/source/eflow_tutorial.rst#L184-L188

https://github.com/yamatolab/current-calculations-for-proteins/blame/master/docs/source/eflow_tutorial.rst#L202

are these ?

**Comment by zorowangtt** [comment]
@flat35hd99 yes. One of them is this line you marked, and another one is in Line202.

**Comment by flat35hd99** [comment]
@zorowangtt I see.
I check develop branch and it was fixed by @OLaprevote 
https://github.com/yamatolab/current-calculations-for-proteins/blob/develop/docs/source/eflow_tutorial.rst

**Comment by flat35hd99** [comment]
@zorowangtt This project has a lot of problems, so I think It is good to wait next release(merge develop)

**Comment by zorowangtt** [comment]
@flat35hd99  I checked the same lines in develop branch, it seems the mistakes still remain. Please help me to check it.
![image](https://user-images.githubusercontent.com/75515371/132274317-c165fb82-72a5-4eb2-9ec9-f9cbd75062ea.png)

**Comment by flat35hd99** [comment]
@zorowangtt oh, I'm sorry, you're right. That part did be maintained.
